
INFO6105 Instructor: Dr. Handan Liu

Homework 1  

Grading: total 100 points.


In [5]:
import numpy as np
np.array([1,2,3])


array([1, 2, 3])

In [8]:
import numpy as np
x=[1,2]
np.asarray(x)


array([1, 2])

In [9]:
np.ones((3,2), dtype =float )

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.full((2,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [13]:
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [17]:
a =np.zeros(10)
b =np.zeros(5)
print (a)
print (b)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


In [21]:
np.random.random((3,3,3))


array([[[0.54170093, 0.15238442, 0.73260187],
        [0.15791692, 0.18907748, 0.17840232],
        [0.87083686, 0.93831031, 0.83966599]],

       [[0.17337547, 0.60494336, 0.56001971],
        [0.2769287 , 0.0206169 , 0.6815354 ],
        [0.41824332, 0.43704088, 0.65894489]],

       [[0.67765449, 0.08542727, 0.9903295 ],
        [0.57518046, 0.24249308, 0.25797542],
        [0.71659409, 0.11272551, 0.92924582]]])

In [23]:
np.arange(10,22).reshape((3,4))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [24]:
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [44]:
np.random.seed(10)

In [42]:
X1= np.random.uniform(0,1 , size=(3,2))
X1

array([[0.00394827, 0.51219226],
       [0.81262096, 0.61252607],
       [0.72175532, 0.29187607]])

In [41]:
X2= np.random.randint(0,4 , size=(3,2))
X2

array([[0, 2],
       [0, 3],
       [0, 0]])

In [45]:
np.split(np.arange(1,10),[4,6])

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

In [52]:
x= np.arange(0,16).reshape(4,4)
np.hsplit(x, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [71]:
x= np.arange(5,46,5).reshape(3,3)

#slicing to get the sub-array
y = x[0:2, 1:3]
print(y)

[[10 15]
 [25 30]]


In [72]:
#getting individual element value 20
z = x[1:2,0:1]
print(z)

[[20]]


In [82]:
x = np.array([[1, 2, 3],[4, 5, 6]])
y = np.array([[7, 8, 9],[10, 11, 12]])
z = np.concatenate((x,y), axis=1)
print(z)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [84]:
x = np.array([3,6,9,25,10,8])
print(x[1:])

[ 6  9 25 10  8]


In [85]:
print(x[:5])

[ 3  6  9 25 10]


In [88]:
print(x[0::2])

[ 3  9 10]


In [89]:
print(x[1:])

[ 6  9 25 10  8]


In [90]:
print(x[::-1])

[ 8 10 25  9  6  3]


In [92]:
x = np.arange(0,32).reshape(8,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [93]:
x[0,2] = 0
print(x)

[[ 0  1  0  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [99]:
print(x[:,1])

[ 1  5  9 13 17 21 25 29]


In [101]:
print(x[0:3,0:3])

[[ 0  1  0]
 [ 4  5  6]
 [ 8  9 10]]


In [103]:
x = np.random.randn(1000)

mean = x.mean()
print("Average of the array elements is: %.5f" %mean)

std = x.std()
print("Standard deviation of the array elements: %.5f" %std)

var = x.var()
print("Variance of the array elements: %.5f" %var)

Average of the array elements is: -0.01109
Standard deviation of the array elements: 0.99477
Variance of the array elements: 0.98958


In [115]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
c = a + b[:, np.newaxis]
print(c)

[[ 1. 11. 21. 31.]
 [ 2. 12. 22. 32.]
 [ 3. 13. 23. 33.]]


In [116]:
x = np.arange(4)
y = np.ones(5)
z = x[:, np.newaxis] + y
print(z)

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


In [117]:
a = np.arange(1,7)
b = np.arange(1,7).reshape(6,1)
c = a*b
print(c)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [110]:
for i in range(1,7):
    for j in range(1,7):
        print(i*j, end="\t")
    print("\n")    

1	2	3	4	5	6	

2	4	6	8	10	12	

3	6	9	12	15	18	

4	8	12	16	20	24	

5	10	15	20	25	30	

6	12	18	24	30	36	



In [121]:
x1 = np.random.rand(10,3)
print(x1)

[[0.02865114 0.15312442 0.18278299]
 [0.12163344 0.16563768 0.09104224]
 [0.52194354 0.84183127 0.3422337 ]
 [0.74135821 0.78773808 0.85992912]
 [0.17859363 0.37672864 0.62837012]
 [0.13264335 0.59663812 0.87879439]
 [0.19928425 0.06098229 0.55326377]
 [0.8115738  0.7007786  0.04423432]
 [0.74638328 0.66811426 0.54301977]
 [0.28593769 0.8973488  0.55557467]]


In [122]:
x2 = np.mean(x1, axis=0)
print(x2)

[0.37680023 0.52489222 0.46792451]


In [123]:
x3=x1-x2
print(x3)

[[-0.34814909 -0.3717678  -0.28514152]
 [-0.2551668  -0.35925453 -0.37688227]
 [ 0.14514331  0.31693905 -0.12569081]
 [ 0.36455797  0.26284586  0.39200461]
 [-0.1982066  -0.14816357  0.16044561]
 [-0.24415688  0.0717459   0.41086988]
 [-0.17751598 -0.46390992  0.08533926]
 [ 0.43477357  0.17588639 -0.42369019]
 [ 0.36958305  0.14322204  0.07509527]
 [-0.09086254  0.37245658  0.08765016]]


In [125]:
a= np.mean(x3)
print(a)

-3.8857805861880476e-17
